version: '1'
process: train
input:
  file:
    type: raw
    filename: './path/to/file.ext'
windowing:
  enable: true
  parameters:
    length: 60
    function:
      label: none
    overlap: 0
features:
  - label: average
    container: core-features
  - label: std_dev
    container: core-features
algorithm:
  name: random_forest
  container: core-py-sk
  parameters:
    example: parameter
